### ISSUE TITLE
Apply for Datasets

### ISSUE THREAD

**Issue by VictorZoo** [stuckerc/ResDepth#2]
Dear Author,

Hi! Sorry to bother you.

I am very interested in your brilliant works ResDepth for 3D reconstruction! I wondered if there are **original datasets** can be dowloaded (i.e. Zurich), so that can understand this paper better.

I only find the _Zurich_GT.tif_ files. I would be grateful if you could give me the dataset and I will utilize it only for academic research.

**Comment by stuckerc** [comment]
Hi,

Due to the commercial nature of VHR imagery, we cannot share our datasets. Please have a look at our demo, which provides the data of one sample, i.e., a geographic region of the size 64&times;64 m in world coordinates (256&times;256 pixels):
- ground truth DSM
- initial DSM (conventional reconstruction)
- multiple WV satellite views
- building mask
- image list
- image pair list
